name: algo_project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  #stack: ^0.2.1
  collection: ^1.17.2
  popover: ^0.2.8+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: arabic
      fonts:
        - asset: assets/fonts/NotoKufiArabic-VariableFont_wght.ttf
    - family: english
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
